services:
  docs:
    image: specialty_bookings_system_local_docs
    container_name: specialty_bookings_system_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./specialty_bookings_system:/app/specialty_bookings_system:z
    ports:
      - '9000:9000'
    command: /start-docs
